server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG

spring:
  application:
    name: gateway-service
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=0
        - id: student-service
          uri: http://localhost:8082
          predicates:
            - Path=/students/**
        - id: course-service
          uri: http://localhost:8083
          predicates:
            - Path=/courses/**
        - id: tracking-service
          uri: http://localhost:8084
          predicates:
            - Path=/tracking/**
          filters:
            - StripPrefix=1
        - id: enrollment-service
          uri: http://localhost:8085
          predicates:
            - Path=/enrollments/**
        - id: feature-service
          uri: http://localhost:8086
          predicates:
            - Path=/weekly-features/**
          filters:
            - StripPrefix=0
        - id: graph-service
          uri: http://localhost:8087
          predicates:
            - Path=/graph/**
          filters:
            - StripPrefix=0
